version: "3"

networks:
    public:
        driver: bridge
    internal:
        driver: bridge
        internal: true

volumes:
    polnpy_mongo_data:
        external: true

services:
    polnpy_api:
        image: matthieu88160/polnpy:latest
        ports:
            - 81:80
        networks:
            - internal
            - public
        depends_on:
            - mongo
    
    mongo:
        image: mongo
        networks:
            - internal
        volumes:
            - polnpy_mongo_data:/data/db

    redis:
        image: redis
        networks:
            - internal
