version: "3"

networks:
    public:
        driver: bridge
    internal:
        driver: bridge
        internal: true

volumes:
    mongo_data:

services:
    polnpy_api:
        build: ../image/php7.2-apache
        ports:
            - 80:80
        networks:
            - internal
            - public
        depends_on:
            - mongo
    
    mongo:
        image: mongo
        networks:
            - internal
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis
        networks:
            - internal
